name: Assign Milestone

on:
  pull_request_target:
    types: [opened]

permissions:
  pull-requests: write
  contents: read

env:
  GH_TOKEN: ${{ github.token }}

jobs:
  build:
    name: Assign Milestone
    runs-on: ubuntu-24.04

    steps:
      - name: Checkout code
        uses: actions/checkout@692973e3d937129bcbf40652eb9f2f61becf3332 # v4.1.7
        with:
          ref: ${{ github.base_ref }}

      - name: Assign Milestone
        run: |
          # Ensure the content we sed from version.go is sanitized and match the correct format
          VERSION=$(sed -n 's/.*versionName.*\"\([[:digit:]\.]*\).*\"/\1/p' ./go/vt/servenv/version.go)
          if [[ ! "$VERSION" =~ ^[0-9]+\.[0-9]+\.[0-9]+$ ]]; then
            echo "Invalid version format: $VERSION"
            exit 1
          fi

          gh pr edit ${{ github.event.number }} --milestone "v$VERSION"
